// Code generated by protoc-gen-go.
// source: notification.proto
// DO NOT EDIT!

package protobuf

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Notification struct {
	User             *string `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Message          *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}

func (m *Notification) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *Notification) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

type Log struct {
	Notification     *Notification `protobuf:"bytes,1,req,name=notification" json:"notification,omitempty"`
	SendingTime      *int32        `protobuf:"varint,2,req,name=sendingTime" json:"sendingTime,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}

func (m *Log) GetNotification() *Notification {
	if m != nil {
		return m.Notification
	}
	return nil
}

func (m *Log) GetSendingTime() int32 {
	if m != nil && m.SendingTime != nil {
		return *m.SendingTime
	}
	return 0
}

func init() {
}
